### ISSUE TITLE
GraphQL authentication with withApiAuthRequired function

### ISSUE THREAD

**Issue by softshipper** [jamesqquick/nextjs-crash-course-fauna-swr-react-hook-form-tailwind#3]
Hi @jamesqquick 
I have question regarding to `withApiAuthRequired` function. 
I have protected the GraphQL server in the API with the function `withApiAuthRequired` as the following:
```
const server = new ApolloServer({
    schema,
    context: () => new Context()
});
const handler = server.createHandler({path: "/api/graphql"});

export const config = {
    api: {
        bodyParser: false,
    },
};

export default withApiAuthRequired((req: NextApiRequest, res: NextApiResponse<void>) => {
    return handler(req, res);
});
```
When I make a request with GraphQL client to the server with the following HTTP header:
```
 {headers: {"Authorization": `Bearer ${session.accessToken}`}}
```
I have got the response `{ '1928170296': { error: { graphQLErrors: [], networkError: 'Error: Unauthorized' } } }`. 

The full code of the client implementation:
```
const session = await getSession(req, res);
const ssrCache = ssrExchange({isClient: false});
const client = initUrqlClient({
    url: addr.gql,
    exchanges: [dedupExchange, cacheExchange, ssrCache, fetchExchange],
    fetchOptions: () => {
        return session.accessToken === undefined ? {} : {headers: {"Authorization": `Bearer ${session.accessToken}`}}
    }
}, false);
```
The GraphQL client can not be authenticated to the server. What am I doing wrong?

Best regards,
Softshipper

**Comment by jamesqquick** [comment]
This graphql integration is new for me, so I'm not sure what to do right off hand. Would you be open to setting up some 1:1 time to look at this together next week? Want to email me at james.quick@auth0.com

**Comment by softshipper** [comment]
@jamesqquick thanks for your answer. I realized, what I want to do does not make sense. 

Thanks so much. Your videos on Youtube are awesome. I love it.
